Fix NoMethodError (undefined method `parse' for Time:Class)
When called on a place where "time" has not been required, it would cause Time.parse to raise NoMethodError.